#before_script:
#    - docker-php-ext-enable igbinary xdebug zip

variables:
  # Timezone will be used both for system and php date.timezone php.ini value
  TIMEZONE: "Europe/Moscow"

php-5.5:
  image: tetraweb/php:5.5
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh

php-5.6:
  image: tetraweb/php:5.6
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh

php-7.0:
  image: tetraweb/php:7.0
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh

php-7.1:
  image: tetraweb/php:7.1
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh
